name: pull_request
on: pull_request
jobs:
  lint-unit-tests:
    name: Lint + Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install packages
        run:
          dart pub get
      - name: Lint
        run: 
          dart analyze
      - name: Unit tests
        run:
          dart test
